# Generated by Django 5.0 on 2026-03-02 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_report"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopCommenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("comment_count", models.IntegerField(default=0)),
            ],
        ),
    ]
