# Generated by Django 5.2.12 on 2026-03-05 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_review_rating'),
        ('movies', '0004_topcommenter'),
    ]

    operations = [
    ]
